services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: nord
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - ./app:/opt/app
    db:
        container_name: nord_db
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USER}
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 5s
            timeout: 5s
            retries: 5
        image: mysql:8.4.2
        ports:
            - ${DB_PORT}:3306
        restart: on-failure
        volumes:
            - ./docker/db/data:/var/lib/mysql
