framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                middleware:
                    - doctrine_transaction
                default_middleware: allow_no_handlers
            query.bus:

        default_bus: command.bus

        transports:
            sync: 'sync://'
